spring.application.name=ecommerce

spring.datasource.url=jdbc:mysql://localhost:${DB_PORT}/ecommerce?useSSL=false&serverTimezone=UTC

spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update